// ChangelingGameplayTags.h
//
// Native tags, so C++ and Blueprint reference one source of truth. A tag typed by
// hand into a DataTable row is a tag that silently stops matching the day someone
// renames it; these will not compile if they drift.
//
// Art.*    the verbs of faerie magic
// Realm.*  what a cantrip may be aimed at
// State.Enchanted marks who can perceive chimerical things at all.

#pragma once

#include "NativeGameplayTags.h"

namespace ChangelingTags
{
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Art_Autumn);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Art_Chicanery);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Art_Chronos);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Art_Contract);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Art_DragonsIre);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Art_Legerdemain);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Art_Metamorphosis);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Art_Naming);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Art_Oneiromancy);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Art_Primal);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Art_Pyretics);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Art_Skycraft);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Art_Soothsay);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Art_Sovereign);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Art_Spring);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Art_Summer);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Art_Wayfare);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Art_Winter);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Realm_Fae);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Realm_Actor);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Realm_Nature);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Realm_Prop);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Realm_Time);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Realm_Scene);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cantrip_Manifestation_Chimerical);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cantrip_Manifestation_Wyrd);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cantrip_State_Casting);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cantrip_State_Channelling);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cantrip_State_Tainted);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cantrip_Event_EffectStart);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cantrip_Event_Recovered);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cantrip_Data_GlamourCost);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enchanted);
	CHANGELING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Banality_Heavy);
}
